/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.baseDeConocimiento.BaseDeConocimiento;
import controller.clausula.clausula;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Point;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.Reader;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author jdani
 */
public class miProlog extends javax.swing.JFrame {

    private Point initialClick;
    private boolean isPlaceholderDisplayed;
    String placeholderText = "p :- q ,r . \n" + "p . \n" + "r :- fail ,s . \n";  //esto es solo para el placeholder del textArea

    public BaseDeConocimiento baseDeConocimiento;

    /**
     * Creates new form miProlog
     */
    public miProlog() {
        initComponents();
        this.setLocationRelativeTo(null);

        jTextArea1.setText(placeholderText);
        jTextArea1.setForeground(new Color(230, 220, 210));
        isPlaceholderDisplayed = true;
        
        JOptionPane.showMessageDialog(null,"procure cargar sigma en cada cambio que haga :) \n  y antes de hacer una consulta !");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 0, 51));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 0, 51));
        jButton1.setText("X");
        jButton1.setToolTipText("salir ? ");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(255, 204, 204));
        jTextField1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(102, 0, 51));
        jTextField1.setText("?-");
        jTextField1.setToolTipText(":) Presione enter para consular");
        jTextField1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Roboto", 1, 8)); // NOI18N
        jButton3.setForeground(new java.awt.Color(153, 0, 51));
        jButton3.setText("consult");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 342, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextField1))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 40));

        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(73, 18, 15));
        jTextArea1.setRows(5);
        jTextArea1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextArea1FocusLost(evt);
            }
        });
        jTextArea1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextArea1MouseClicked(evt);
            }
        });
        jPanel1.add(jTextArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 600, 440));

        jPanel3.setBackground(new java.awt.Color(12, 75, 131));
        jPanel3.setForeground(new java.awt.Color(51, 51, 51));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 0, 0));
        jButton2.setText("CARGAR SIGMA");
        jButton2.setToolTipText("procura que el campo de texto tenga clausulas validas");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/1f989.png"))); // NOI18N

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(51, 0, 102));
        jTextField2.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(102, 255, 102));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setBorder(null);
        jTextField2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel2.setText("PROLOG 1.0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2)
                .addGap(145, 145, 145)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 230, 440));

        Menu.setName("menu"); // NOI18N

        jMenu5.setText("File    ");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Consult...                     ");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Save as...                      ");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);
        jMenu5.add(jSeparator1);

        jMenuItem5.setText("Exit...");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem5);

        Menu.add(jMenu5);

        jMenu6.setText(" EjemplosDePrueba     ");

        jMenuItem3.setText("Ejemplo sin backtrack                 ");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem3);

        jMenuItem4.setText("Ejemplo2 con backtrack                ");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem4);

        jMenuItem6.setText("Ejemplo3 Manejando Fail");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem6);

        jMenuItem7.setText("Ejemplo4 Manejando Cut");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem7);

        jMenuItem8.setText("Ejemplo5 Manejando Cut");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem8);

        Menu.add(jMenu6);

        jMenu2.setText("Preferences     ");
        Menu.add(jMenu2);

        jMenu1.setText("     Help         ");
        Menu.add(jMenu1);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 833, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:     ---------------- importar un archivo txt
        JFileChooser fileChooser = new JFileChooser();

        FileNameExtensionFilter filter1 = new FileNameExtensionFilter("Archivos de texto", "txt");
        FileNameExtensionFilter filter2 = new FileNameExtensionFilter("Archivos de Prolog", "pl");
        fileChooser.setFileFilter(filter1);
        fileChooser.setFileFilter(filter2);

        JOptionPane.showMessageDialog(null, "procure seleccionar un archivo en formato .txt o .pl");
        int seleccion = fileChooser.showOpenDialog(jTextArea1);

        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File fichero = fileChooser.getSelectedFile();
            if (fichero.getName().endsWith("txt") || fichero.getName().endsWith(".pl")) {
                // Aquí debemos abrir y leer el fichero.
                try ( Reader r = new FileReader(fichero.getPath());  BufferedReader br = new BufferedReader(r)) {
                    String lineaEnTurno;
                    String textoEnteroDelTxt = "";

                    BaseDeConocimiento baseDeConocimientoDelTxt = new BaseDeConocimiento();
                    do {
                        lineaEnTurno = br.readLine();

                        if (lineaEnTurno != null) {
                            baseDeConocimientoDelTxt.Agregar(new clausula(lineaEnTurno));
                            textoEnteroDelTxt += lineaEnTurno + '\n';
                        }
                    } while (lineaEnTurno != null);

                    jTextArea1.setText(textoEnteroDelTxt);
                    this.baseDeConocimiento = baseDeConocimientoDelTxt;
                    JOptionPane.showMessageDialog(null, """
                                                        se cargo a la base de Conocimiento ! 
                                                         procede a introducir un goal :) !""");

                } catch (Exception e) {
                    System.out.println(e);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Seleccionar formato Valido");
            }

        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:        CARGAR BASE DE CONOCIMIENTO 
        BaseDeConocimiento nuevaBaseDeConocimiento = new BaseDeConocimiento();
        if (!jTextArea1.getText().isBlank() && !isPlaceholderDisplayed) {
            String[] text = jTextArea1.getText().trim().split("\\.");
            for (String text1 : text) {
                nuevaBaseDeConocimiento.Agregar(new clausula(text1));
            }

            this.baseDeConocimiento = nuevaBaseDeConocimiento;
            JOptionPane.showMessageDialog(null, "se cargo a la base de conocimiento!");
        } else {
            String message = """
                             "Advertencia "
                             considera rellenar el campo de texto! 
                             si no estas seguro, prueba con un ejemplo en la barra del menu! 
                             y presiona el boton CargarSigma""";
//            JOptionPane.showMessageDialog(new JFrame(), message, "GOAL",
//                    JOptionPane.ERROR_MESSAGE);
            JOptionPane.showMessageDialog(null, message, "SIGMA ESTA VACÌO", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:          CARGANDO EJEMPLO DE UNA CLASE EN EL EDITOR 
        jTextArea1.setText("m :- s, t, a ." + '\n'
                + "m :- s . " + '\n'
                + "s :- a ." + '\n'
                + "t :- b ." + '\n'
                + "b  . " + '\n'
                + "a :- .");

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:   //  GOAL   ----------------------------------------------
        char c = (char) evt.getKeyCode();
        if (c == KeyEvent.VK_ENTER) {
            if (this.baseDeConocimiento != null && !this.baseDeConocimiento.isEmpty()) {
                String goal = jTextField1.getText().trim().replace(" ", "").replace("?-", "").replace(".", "");
                if (!"".equals(goal)) {
                    if (this.baseDeConocimiento.Deriva(goal)) {
                        jTextField2.setForeground(new Color(66, 255, 66));
                        jTextField2.setText("True");
                    } else {
                        jTextField2.setForeground(new Color(255, 66, 66));
                        jTextField2.setText("False");
                    }
                } else {
                    String message = """
                                     "Ups! ocurrio un error "
                                     considera introducir un goal valido! 
                                     goal is null """;
                    JOptionPane.showMessageDialog(new JFrame(), message, "GOAL",
                            JOptionPane.ERROR_MESSAGE);
                }

            } else {
                jButton2.setBackground(new Color(224, 77, 1));

                String message = """
                                 "Ups! ocurrio un error "
                                 considera cargar la base de conocimiento a memoria
                                 sigma is null or not exist""";
                JOptionPane.showMessageDialog(new JFrame(), message, "Sigma",
                        JOptionPane.ERROR_MESSAGE);
                jButton2.setBackground(new Color(250, 250, 250));

            }
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        // TODO add your3 handling code here:
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:   EJEMPLO 2 ------------------------------
        jTextArea1.setText(
                "a :- b, j , q ." + '\n'
                + "a :- c  . " + '\n'
                + "p :- b, q , j ." + '\n'
                + "p :- b , s ." + '\n'
                + "m  . " + '\n'
                + "b :- m . " + '\n'
                + "c :- t , s . " + '\n'
                + "m :- a ,s . " + '\n'
                + "t :-  . " + '\n'
                + "s :- r ,q ." + '\n'
                + "r :- w ,y ." + '\n'
                + "s ." + '\n'
        );
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:   //  GOAL   ----------------------------------------------
        if (this.baseDeConocimiento != null && !this.baseDeConocimiento.isEmpty()) {
            String goal = jTextField1.getText().trim().replace(" ", "").replace("?-", "").replace(".", "");
            if (!"".equals(goal)) {
                if (this.baseDeConocimiento.Deriva(goal)) {
                    jTextField2.setForeground(new Color(66, 255, 66));
                    jTextField2.setText("True");
                } else {
                    jTextField2.setForeground(new Color(255, 66, 66));
                    jTextField2.setText("False");
                }
            } else {
                String message = """
                                 "Ups! ocurrio un error "
                                 considera introducir un goal valido! 
                                 goal is null """;
                JOptionPane.showMessageDialog(new JFrame(), message, "GOAL",
                        JOptionPane.ERROR_MESSAGE);
            }

        } else {
            jButton2.setBackground(new Color(224, 77, 1));

            String message = """
                             "Ups! ocurrio un error "
                             considera cargar la base de conocimiento a memoria antes de consultar
                             sigma is null or not exist
                             o dirigete al menu y consulta un archivo""";
            JOptionPane.showMessageDialog(new JFrame(), message, "Sigma",
                    JOptionPane.ERROR_MESSAGE);
            jButton2.setBackground(new Color(250, 250, 250));

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:                     GUARDAR ARCHIVO DE TEXTO 

        LocalTime horaActual = LocalTime.now();
        DateTimeFormatter formatoHora = DateTimeFormatter.ofPattern("HH:mm:ss");
        String horaActualTexto = horaActual.format(formatoHora).replace(":", "-");

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("GUARDAR BASE DE CONOCIMIENTO");

        FileNameExtensionFilter filter1 = new FileNameExtensionFilter("Archivos de texto", "txt");  //------filtros  pl y txt
        FileNameExtensionFilter filter2 = new FileNameExtensionFilter("Archivos de Prolog", "pl");
        fileChooser.setFileFilter(filter1);
        fileChooser.setFileFilter(filter2);

        System.out.println(horaActualTexto);
        String nombreDeComoSeGuardaraElArchivo = "BaseDeConocimiento".concat(horaActualTexto).concat(".pl");
        fileChooser.setSelectedFile(new File(nombreDeComoSeGuardaraElArchivo));

        int seleccion = fileChooser.showSaveDialog(jTextArea1);

        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File fichero = fileChooser.getSelectedFile();
            String path = fichero.getPath();
            if (fichero.getPath().endsWith(".txt") || fichero.getPath().endsWith(".pl")) {
                File file = new File(path);
                try {
                    file.createNewFile();
                    FileWriter fw = new FileWriter(file);
                    BufferedWriter bw = new BufferedWriter(fw);
                    bw.write(this.baseDeConocimiento.toString());
                    bw.close();
                    JOptionPane.showMessageDialog(null, "Archivo guardado! ");
                } catch (Exception e) {
                    System.out.println("ocurrio un error en la ruta seleccionada o la extension");
                }

            } else {
                JOptionPane.showMessageDialog(null, "Seleccionar formato Valido");
            }

        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // ----------------------------------------------ESTO ES SOLO PARA PODER MOVER LA VENTANA LIBREMENTE CON EL MOUSE
        int x = this.getLocation().x + evt.getX() - initialClick.x;
        int y = this.getLocation().y + evt.getY() - initialClick.y;
        this.setCursor(Cursor.HAND_CURSOR);
        this.setLocation(x, y);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // ----------------------------------------------ESTO ES SOLO PARA PODER MOVER LA VENTANA LIBREMENTE CON EL MOUSE
        initialClick = evt.getPoint();

    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        // TODO add your handling code here:
        this.setCursor(Cursor.DEFAULT_CURSOR);
    }//GEN-LAST:event_formMouseReleased

    private void jTextArea1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextArea1MouseClicked
        // TODO add your handling code here:
        if (isPlaceholderDisplayed) {
            jTextArea1.setText(jTextArea1.getText());
            jTextArea1.setForeground(new Color(73, 18, 15));
            isPlaceholderDisplayed = false;
        }
    }//GEN-LAST:event_jTextArea1MouseClicked

    private void jTextArea1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextArea1FocusLost
        // TODO add your handling code here:
//        if (jTextArea1.getText().isEmpty()) {
//            jTextArea1.setText(placeholderText);
//            jTextArea1.setForeground(Color.GRAY);
//            isPlaceholderDisplayed = true;
//        }
    }//GEN-LAST:event_jTextArea1FocusLost

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText(
                "p :- q, r , s ." + '\n'
                + "q :- a, fail  . " + '\n'
                + "q :- j  . " + '\n'
                + "a :- c, d , j ." + '\n'
                + "a :- j , k ." + '\n'
                + "p :- j, k , m . " + '\n'
                + "d :- fail . " + '\n'
                + "j :-  . " + '\n'
                + "p :- k, q  . " + '\n'
                + "s :- fail  . " + '\n'
                + "t :-  . " + '\n'
                + "k :- t . " + '\n'
                + "r :- fail, h,i ." + '\n'
                + "r ." + '\n'
                + "c ." + '\n'
        );
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:   manejando cut
        jTextArea1.setText(
                  "s :- t, u , !, v, w ." + '\n'
                + "u :- a . " + '\n'
                + "a . " + '\n'
                + "v :- b, c ." + '\n'
                + "b ." + '\n'
                + "t ." + '\n'
                + "c . " + '\n'
                + "w  . " + '\n'
        );
        
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText(
                  "s :- t, u , !, v, w ." + '\n'
                + "u :- a . " + '\n'
                + "a . " + '\n'
                + "v :- b, c ." + '\n'
                + "b ." + '\n'
                + "t ." + '\n'
                + "c . " + '\n'
                + "g :- fail . " + '\n'
                + "w  :- f ,! ,g . " + '\n'
                + "w  . " + '\n'
                + "f  . " + '\n'
        );

    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(miProlog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(miProlog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(miProlog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(miProlog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new miProlog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
